version: "3"

services:
  back:
    build: ./back
    networks:
        - alice-network
    ports:
      - 8000:8000
    env_file: ./back/.env
    volumes:
      - $MEDIA_DATA:/django_media
      - $STATIC_DATA:/django_static
      - $OUT_DATA:/django_out
    depends_on:
      - postgres
  nginx:
    build: .
    networks:
        - alice-network
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - $MEDIA_DATA:/django_media:ro
      - $STATIC_DATA:/django_static:ro
    depends_on:
      - back
  postgres:
    image: postgres:latest
    networks:
        - alice-network
    ports:
      - 5433:5432
    env_file: ./postgres/.env
    volumes:
      - $POSTGRES_DATA:/var/lib/postgresql/data

networks:
    alice-network:
        external: true
